# Form implementation generated from reading ui file 'createwidget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 508)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 380, 330))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: white;\n"
"    border-radius: 10px\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 380, 70))
        self.widget_3.setStyleSheet("background-color: \"#51b2d9\";\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 380, 70))
        self.label_2.setStyleSheet("text-transform: uppercase;\n"
"font: 16pt \"Kohne Makina\";\n"
"font-weight: bold;\n"
"color: white")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget_4 = QtWidgets.QWidget(self.frame_2)
        self.widget_4.setGeometry(QtCore.QRect(0, 70, 380, 260))
        self.widget_4.setObjectName("widget_4")
        self.input_name_2 = QtWidgets.QLineEdit(self.widget_4)
        self.input_name_2.setGeometry(QtCore.QRect(90, 50, 200, 30))
        self.input_name_2.setStyleSheet("QLineEdit{\n"
"    padding: 5px 5px;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-radius: 6px;\n"
"    border-color: #51b2d9\n"
"}")
        self.input_name_2.setText("")
        self.input_name_2.setObjectName("input_name_2")
        self.input_age_2 = QtWidgets.QLineEdit(self.widget_4)
        self.input_age_2.setGeometry(QtCore.QRect(90, 100, 200, 30))
        self.input_age_2.setStyleSheet("QLineEdit{\n"
"    padding: 5px 5px;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-radius: 6px;\n"
"    border-color: #51b2d9;\n"
"}")
        self.input_age_2.setText("")
        self.input_age_2.setObjectName("input_age_2")
        self.button_create_2 = QtWidgets.QPushButton(self.widget_4)
        self.button_create_2.setGeometry(QtCore.QRect(70, 180, 240, 30))
        self.button_create_2.setStyleSheet("QPushButton {\n"
"    text-transform: uppercase;\n"
"    font: 12pt \"Kohne Makina\";\n"
"    color: lblack;\n"
"    background-color: #bfffbf;\n"
"    border-style: solid;\n"
"}")
        self.button_create_2.setObjectName("button_create_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Cadastrar novo cliente"))
        self.input_name_2.setPlaceholderText(_translate("Form", "Nome"))
        self.input_age_2.setPlaceholderText(_translate("Form", "Idade"))
        self.button_create_2.setText(_translate("Form", "Cadastrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
