# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("display: flex;\n"
"align-items: center;\n"
"justify-content: center;")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(100, 60, 380, 330))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: white;\n"
"    border-radius: 10px\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 380, 70))
        self.widget.setStyleSheet("background-color: \"#51b2d9\";\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 380, 70))
        self.label.setStyleSheet("text-transform: uppercase;\n"
"font: 16pt \"Kohne Makina\";\n"
"font-weight: bold;\n"
"color: white")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(0, 70, 380, 260))
        self.widget_2.setObjectName("widget_2")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 380, 211))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsDragEnabled|QtCore.Qt.ItemFlag.ItemIsDropEnabled|QtCore.Qt.ItemFlag.ItemIsUserCheckable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsDragEnabled|QtCore.Qt.ItemFlag.ItemIsDropEnabled|QtCore.Qt.ItemFlag.ItemIsUserCheckable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsDragEnabled|QtCore.Qt.ItemFlag.ItemIsDropEnabled|QtCore.Qt.ItemFlag.ItemIsUserCheckable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.tableWidget.setItem(0, 2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.setColumnWidth(0, 10)
        self.tableWidget.setColumnWidth(1, 200)
        self.tableWidget.setColumnWidth(2, 150)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Fixed)
        self.tableWidget.setAlternatingRowColors(True)
        self.button_create = QtWidgets.QPushButton(self.widget_2)
        self.button_create.setGeometry(QtCore.QRect(250, 220, 121, 31))
        self.button_create.setStyleSheet("QPushButton {\n"
"    text-transform: uppercase;\n"
"    font: 12pt \"Kohne Makina\";\n"
"    color: white;\n"
"    background-color: red;\n"
"    border-style: solid;\n"
"}")
        self.button_create.setObjectName("button_create")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCadastrar_novo_cliente = QtGui.QAction(MainWindow)
        self.actionCadastrar_novo_cliente.setObjectName("actionCadastrar_novo_cliente")
        self.actionListar_clientes_existentes = QtGui.QAction(MainWindow)
        self.actionListar_clientes_existentes.setObjectName("actionListar_clientes_existentes")
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.menuMenu.addAction(self.actionCadastrar_novo_cliente)
        self.menuMenu.addAction(self.actionListar_clientes_existentes)
        self.menuMenu.addAction(self.actionSair)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def loadData(self):
        self.tableWidget.setRowCount(0)
        f = open('../data/clients.txt', 'r')
        lines = f.readlines()
        self.tableWidget.setRowCount(int(len(lines)/2))
        cont = 0
        for i in range(0, len(lines), 2):
            ##cl = client.Client(id=cont, name=lines[i], age=lines[i+1])
            ##self.tableWidget.setItem(cl.id, 0, QtWidgets.QTableWidgetItem(cl.id))
            ##self.tableWidget.setItem(cl.id, 1, QtWidgets.QTableWidgetItem(cl.name))
            self.tableWidget.setItem(cont, 0, QtWidgets.QTableWidgetItem(cont))
            ##self.tableWidget.setItem(cl.id, 0, QtWidgets.QTableWidgetItem(cl.id))
            self.tableWidget.setItem(cont, 1, QtWidgets.QTableWidgetItem(lines[i]))
            self.tableWidget.setItem(cont, 3, QtWidgets.QTableWidgetItem(lines[i+1]))

            cont += 1

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Lista de clientes"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Idade"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Kirk"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Teste"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.button_create.setText(_translate("MainWindow", "Excluir"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionCadastrar_novo_cliente.setText(_translate("MainWindow", "Cadastrar novo cliente"))
        self.actionListar_clientes_existentes.setText(_translate("MainWindow", "Listar clientes existentes"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
