# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("display: flex;\n"
"align-items: center;\n"
"justify-content: center;")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(100, 60, 380, 330))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: white;\n"
"    border-radius: 10px\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 380, 70))
        self.widget.setStyleSheet("background-color: \"#51b2d9\";\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 380, 70))
        self.label.setStyleSheet("text-transform: uppercase;\n"
"font: 16pt \"Kohne Makina\";\n"
"font-weight: bold;\n"
"color: white")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(0, 70, 380, 260))
        self.widget_2.setObjectName("widget_2")
        self.input_name = QtWidgets.QLineEdit(self.widget_2)
        self.input_name.setGeometry(QtCore.QRect(90, 50, 200, 30))
        self.input_name.setStyleSheet("QLineEdit{\n"
"    padding: 5px 5px;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-radius: 6px;\n"
"    border-color: #51b2d9\n"
"}")
        self.input_name.setText("")
        self.input_name.setObjectName("input_name")
        self.input_age = QtWidgets.QLineEdit(self.widget_2)
        self.input_age.setGeometry(QtCore.QRect(90, 100, 200, 30))
        self.input_age.setStyleSheet("QLineEdit{\n"
"    padding: 5px 5px;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-radius: 6px;\n"
"    border-color: #51b2d9;\n"
"}")
        self.input_age.setText("")
        self.input_age.setObjectName("input_age")
        self.button_create = QtWidgets.QPushButton(self.widget_2)
        self.button_create.setGeometry(QtCore.QRect(70, 180, 240, 30))
        self.button_create.setStyleSheet("QPushButton {\n"
"    text-transform: uppercase;\n"
"    font: 12pt \"Kohne Makina\";\n"
"    color: lblack;\n"
"    background-color: #bfffbf;\n"
"    border-style: solid;\n"
"}")
        self.button_create.setObjectName("button_create")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCadastrar_novo_cliente = QtGui.QAction(MainWindow)
        self.actionCadastrar_novo_cliente.setObjectName("actionCadastrar_novo_cliente")
        self.actionListar_clientes_existentes = QtGui.QAction(MainWindow)
        self.actionListar_clientes_existentes.setObjectName("actionListar_clientes_existentes")
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.menuMenu.addAction(self.actionCadastrar_novo_cliente)
        self.menuMenu.addAction(self.actionListar_clientes_existentes)
        self.menuMenu.addAction(self.actionSair)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cadastrar novo cliente"))
        self.input_name.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.input_age.setPlaceholderText(_translate("MainWindow", "Idade"))
        self.button_create.setText(_translate("MainWindow", "Cadastrar"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionCadastrar_novo_cliente.setText(_translate("MainWindow", "Cadastrar novo cliente"))
        self.actionListar_clientes_existentes.setText(_translate("MainWindow", "Listar clientes existentes"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
